disabled_rules:
- leading_whitespace
- trailing_whitespace
- line_length
- cyclomatic_complexity
- function_body_length
- function_parameter_count
- orphaned_doc_comment
- vertical_parameter_alignment_on_call
- unused_optional_binding

opt_in_rules:
type_body_length:
    - 1000
    - 1500

file_length:
    warning: 3000
    error: 4000

type_name:
    min_length:
        warning: 1
    max_length:
        warning: 80
        error: 100

identifier_name:
    min_length:
        warning: 1
        
excluded:
  - Notes/Controller/AppDelegate.swift
  - Notes/Controller/SceneDelegate.swift
